// Copyright (c) 2026 Mohsen Zamani / ZamaniDeveloper. See LICENSE.
import {T} from './text.mjs';
const tg=window.Telegram?.WebApp,initData=tg?.initData || '',$=id=>document.getElementById(id);
document.documentElement.lang=T.lang;document.documentElement.dir=T.dir;$('subtitle').textContent=T.subtitle;$('refresh').ariaLabel=T.refresh;
tg?.ready();tg?.expand();
const tabs=[['overview','◈'],['chats','☷'],['projects','▱'],['queue','◷'],['changes','⌘']];
let page='overview',state=null,rows=[],offset=0,more=false,query='',projects=[],queue=[],detail=null,preview=null,pending=false,readPending=false,epoch=0;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
function button(label,fn,cls='secondary'){const b=el('button',label,cls);b.type='button';b.addEventListener('click',fn);b.disabled=pending;return b;}
function notice(text,error=false){$('notice').textContent=text;$('notice').className=error?'error':'';$('notice').hidden=!text;}
async function api(route,body){const response=await fetch(new URL('api/'+route,location.href.split('?')[0]),{method:body?'POST':'GET',headers:{'x-telegram-init-data':initData,...(body?{'content-type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(response.status===401)throw Error(T.auth);if(!response.ok)throw Error(body?T.failed:T.unavailable);return data.result;}
function dialog(title,body,input=false){return new Promise(resolve=>{const d=$('dialog');$('dialog-title').textContent=title;$('dialog-body').textContent=body;$('dialog-label').textContent=title;$('dialog-label').hidden=!input;$('dialog-input').hidden=!input;$('dialog-input').value='';$('dialog-cancel').textContent=T.cancel;$('dialog-confirm').textContent=T.confirm;$('dialog-input').required=input;const done=value=>{d.close();$('dialog-form').onsubmit=null;$('dialog-cancel').onclick=null;d.oncancel=null;resolve(value);};$('dialog-form').onsubmit=e=>{e.preventDefault();done(input?$('dialog-input').value:true);};$('dialog-cancel').onclick=()=>done(null);d.oncancel=e=>{e.preventDefault();done(null);};d.showModal();if(input)$('dialog-input').focus();});}
async function action(value){if(pending)return null;pending=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{const result=await api('action',{...value,key:crypto.randomUUID()});notice(value.action==='send'?(result.queued?T.queuedResult:T.sent):T.saved);return result;}catch(e){notice(e.message,true);return null;}finally{pending=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function badge(text,cls=''){return el('span',text,'badge '+cls);}
function empty(text=T.empty){return el('div',text,'empty');}
function heading(title,lead){const h=el('section',null,'section-head');h.append(el('h1',title));$('content').append(h);if(lead)$('content').append(el('p',lead,'muted'));}
function chatCard(row){const w=state?.chats.find(c=>c.id===row.id),c=el('article',null,'card'),top=el('div',null,'top');top.append(el('h3',row.title),badge(w?.busy?T.working:w?.synced?T.ready:T.notLive,w?.busy?'busy':w?.synced?'live':''));c.append(top,el('div',row.cwd,'path'));if(row.id===state?.selectedId)c.append(badge(T.selected,'live'));if(w?.waiting)c.append(el('p',T.waiting+': '+w.waiting,'muted'));const actions=el('div',null,'actions');actions.append(button(T.open,()=>openChat(row),'primary'),button(T.latest,()=>last(row)));c.append(actions);return c;}
function drawTabs(){const nav=$('tabs');nav.replaceChildren();for(const[key,icon]of tabs){const b=button('',()=>navigate(key),'');b.append(el('span',icon),document.createTextNode(T[key]));if(page===key&&!detail)b.setAttribute('aria-current','page');nav.append(b);}}
function render(){drawTabs();const main=$('content');main.replaceChildren();if(detail)return renderChat();
 if(page==='overview'){const hero=el('section',null,'hero');hero.append(badge(state?.connected?T.connected:T.offline,state?.connected?'live':''),el('h1',T.welcome),el('p',T.lead));main.append(hero);const metrics=el('div',null,'metrics');for(const[number,label]of [[state?.chats.length || 0,T.watched],[state?.chats.filter(c=>c.busy).length || 0,T.active],[state?.waiting || 0,T.waiting]]){const m=el('div',null,'metric');m.append(el('strong',String(number)),el('span',label));metrics.append(m);}main.append(metrics);if(state?.switching)main.append(el('p',T.switching,'muted'));main.append(el('h2',T.watched));const grid=el('div',null,'cards');for(const row of state?.chats || [])grid.append(chatCard(row));main.append(grid.children.length?grid:empty());}
 if(page==='chats'){heading(T.chats);const form=el('form',null,'search'),input=el('input');input.placeholder=T.search;input.ariaLabel=T.search;input.value=query;const submit=button(T.searchAction,()=>{},'primary');submit.type='submit';form.append(input,submit);form.onsubmit=e=>{e.preventDefault();query=input.value;offset=0;loadPage();};main.append(form);const grid=el('div',null,'cards');for(const row of rows)grid.append(chatCard(row));main.append(grid.children.length?grid:empty());const nav=el('div',null,'actions');if(offset)nav.append(button(T.previous,()=>{offset=Math.max(0,offset-20);loadPage();}));if(more)nav.append(button(T.next,()=>{offset+=20;loadPage();}));main.append(nav);}
 if(page==='projects'){heading(T.projects);const grid=el('div',null,'cards');for(const p of projects){const c=el('article',null,'card');c.append(el('h3',p.name));for(const r of p.roots)c.append(el('div',r.path,'path'));const a=el('div',null,'actions');a.append(button(T.chooseProject,()=>{query=p.roots[0]?.path || p.name;offset=0;navigate('chats');},'primary'),button(T.newchat,async()=>{const name=await dialog(T.name,'',true);if(!name?.trim())return;const result=await action({action:'create',name,projectId:p.id});if(result){await openChat(result);}}));c.append(a);grid.append(c);}main.append(grid.children.length?grid:empty());}
 if(page==='queue'){heading(T.queue,T.queueLead);main.append(badge(T.waiting+': '+(state?.waiting || 0),'live'));const grid=el('div',null,'cards');for(const e of queue){const c=el('article',null,'card');c.append(el('h3',e.title),badge(T[e.status] || T.unknown,e.status==='uncertain'?'error':''),el('p',e.preview,'queue-preview'));if(['queued','uncertain'].includes(e.status))c.append(button(T.remove,async()=>{if(await dialog(T.remove,T.removeQuestion)){await action({action:'cancel',entryId:e.id});await loadPage();}},'danger'));grid.append(c);}main.append(grid.children.length?grid:empty());}
 if(page==='changes'){heading(T.changes,T.diffLead);const w=state?.chats.find(c=>c.id===state.selectedId);if(w)main.append(el('p',w.title,'muted'));drawChanges(w?.changes || []);}
}
function drawChanges(changes){if(!changes.length){$('content').append(empty(T.noDiff));return;}for(const change of changes){const c=el('article',null,'card');c.append(el('div',change.path,'path'),badge(change.kind || 'edit'));const pre=el('pre',null,'diff');for(const line of change.diff.split('\n')){const span=el('span',line+'\n',line.startsWith('@@')?'diff-meta':line.startsWith('+')?'add':line.startsWith('-')?'del':'');pre.append(span);}c.append(pre);if(change.truncated)c.append(el('small',T.truncated));$('content').append(c);}}
async function last(row){try{const r=await api('last?id='+encodeURIComponent(row.id));detail=row;preview=r.message;render();}catch(e){notice(e.message,true);}}
async function openChat(row){detail=row;preview=null;render();await refreshState();}
function renderChat(){const main=$('content'),w=state?.chats.find(c=>c.id===detail.id);main.append(button('‹ '+T.back,()=>{detail=null;preview=null;render();}));heading(detail.title,w?.synced?T.live:T.notLive);if(w){main.append(badge(w.busy?T.working:T.ready,w.busy?'busy':'live'),el('div',w.cwd,'path'));if(w.model)main.append(el('small',T.model+': '+w.model));}
 if(state?.selectedId!==detail.id || !w?.synced)main.append(button(T.select,async()=>{const result=await action({action:'select',threadId:detail.id});if(result)await refreshState();},'primary'));
 const list=el('div',null,'messages'),messages=preview?[preview]:(w?.messages || []);for(const m of messages){const n=el('article',null,'message '+(m.role==='User'?'user':''));n.append(el('strong',m.role==='User'?T.user:m.role),el('p',m.text));if(m.truncated)n.append(el('small',T.truncated));list.append(n);}main.append(list.children.length?list:empty(T.noMessages));
 if(w?.synced && state?.selectedId===detail.id){const form=el('form',null,'composer'),text=el('textarea');text.placeholder=T.message;text.ariaLabel=T.message;text.maxLength=30000;text.required=true;text.rows=3;text.id='composer-text';const send=button(T.send,()=>{},'primary');send.type='submit';form.append(text,send);form.onsubmit=async e=>{e.preventDefault();const content=text.value;if(!content.trim())return;const r=await action({action:'send',threadId:w.id,text:content});if(r){text.value='';preview=null;await refreshState();}};main.append(form);if(w.busy){const a=el('div',null,'actions');a.append(button(T.steer,async()=>{const text=await dialog(T.steer,'',true);if(text?.trim()){await action({action:'steer',threadId:w.id,turnId:w.turnId,text});await refreshState();}},'primary'),button(T.stop,async()=>{if(await dialog(T.stop,T.stopQuestion)){await action({action:'stop',threadId:w.id,turnId:w.turnId});await refreshState();}},'danger'));main.append(a);}}
}
async function refreshState(){if(readPending)return;readPending=true;try{state=await api('state'+(detail?'?id='+encodeURIComponent(detail.id):''));if(pending||$('dialog').open)return;const text=$('composer-text'),draft=text?.value,focused=document.activeElement===text,selection=[text?.selectionStart,text?.selectionEnd],scroll=window.scrollY;render();if(draft&&$('composer-text'))$('composer-text').value=draft;if(focused){$('composer-text')?.focus({preventScroll:true});$('composer-text')?.setSelectionRange(...selection);}window.scrollTo(0,scroll);}catch(e){notice(e.message,true);}finally{readPending=false;}}
async function loadPage(){const ticket=++epoch;try{const results=await Promise.all([api('state'),page==='chats'?api('chats?q='+encodeURIComponent(query)+'&offset='+offset):page==='projects'?api('projects'):page==='queue'?api('queue'):Promise.resolve(null)]);if(ticket!==epoch)return;state=results[0];const data=results[1];if(page==='chats'){rows=data.rows;more=data.more;}if(page==='projects')projects=data.rows;if(page==='queue')queue=data.entries;render();}catch(e){notice(e.message,true);}}
function navigate(key){if(pending)return;page=key;detail=null;preview=null;render();loadPage();window.scrollTo(0,0);}
$('refresh').addEventListener('click',()=>{notice('');detail?refreshState():loadPage();});
if(!initData){notice(T.auth,true);$('content').append(empty(T.auth));$('refresh').disabled=true;}else{render();loadPage();setInterval(()=>{if(!document.hidden&&!pending&&!$('dialog').open){if(detail||page==='overview'||page==='changes')refreshState();else if(page==='queue')loadPage();}},3000);}
tg?.onEvent('themeChanged',()=>{document.documentElement.style.colorScheme=tg.colorScheme;});
